# Generated by Django 3.2.11 on 2022-06-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accountNumber',
            field=models.IntegerField(default=0),
        ),
    ]
