# Generated by Django 3.2.11 on 2022-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_accountnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transactionType',
            field=models.CharField(choices=[('WD', 'Withdrawal'), ('DS', 'Deposit')], default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accountNumber',
            field=models.IntegerField(),
        ),
    ]
