# Generated by Django 3.2.11 on 2022-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accountBalance',
            field=models.FloatField(default=0),
        ),
    ]
