# Generated by Django 3.2.11 on 2022-06-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customer_accountbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accountNumber',
            field=models.CharField(max_length=10),
        ),
    ]
