# Generated by Django 3.2.11 on 2022-07-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customer_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
